apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-example-prod

resources:
  - ../../base

images:
  - name: amertz08/gitops-example
    newTag: 58b19ea05a868cc4d9f590f4173f91038fd9441e
  - name: amertz08/gitops-example-worker
    newTag: 163f5be908fe14dc9e7c915092d686008f930694

replicas:
  - name: gitops-example
    count: 2
