apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: amertz08/gitops-example
    newTag: 1ebd9e4de4f4171695c004ce249a355df3044107
