apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: amertz08/gitops-example
    newTag: 0abd399f7680fdcfa720788c673533dbd0ef274b

configMapGenerator:
  - name: gitops-example-config
    literals:
      - LOG_LEVEL=debug
      - PORT=1323
