apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: amertz08/gitops-example
    newTag: d697c0d74b03388282e55a40d49b1855d96a1994

configMapGenerator:
  - name: gitops-example-config
    literals:
      - LOG_LEVEL=info
      - PORT=1323
