apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-example-feature-add-version-endpoint
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Amertz08/gitops-example
    targetRevision: feature/add-version-endpoint
    path: deploy/base
    kustomize:
      images:
        - amertz08/gitops-example:feature-add-version-endpoint-latest
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-example-feature-add-version-endpoint
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
